require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UniversidadsController do

  # This should return the minimal set of attributes required to create a valid
  # Universidad. As you add validations to Universidad, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "nombre" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UniversidadsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all universidads as @universidads" do
      universidad = Universidad.create! valid_attributes
      get :index, {}, valid_session
      assigns(:universidads).should eq([universidad])
    end
  end

  describe "GET show" do
    it "assigns the requested universidad as @universidad" do
      universidad = Universidad.create! valid_attributes
      get :show, {:id => universidad.to_param}, valid_session
      assigns(:universidad).should eq(universidad)
    end
  end

  describe "GET new" do
    it "assigns a new universidad as @universidad" do
      get :new, {}, valid_session
      assigns(:universidad).should be_a_new(Universidad)
    end
  end

  describe "GET edit" do
    it "assigns the requested universidad as @universidad" do
      universidad = Universidad.create! valid_attributes
      get :edit, {:id => universidad.to_param}, valid_session
      assigns(:universidad).should eq(universidad)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Universidad" do
        expect {
          post :create, {:universidad => valid_attributes}, valid_session
        }.to change(Universidad, :count).by(1)
      end

      it "assigns a newly created universidad as @universidad" do
        post :create, {:universidad => valid_attributes}, valid_session
        assigns(:universidad).should be_a(Universidad)
        assigns(:universidad).should be_persisted
      end

      it "redirects to the created universidad" do
        post :create, {:universidad => valid_attributes}, valid_session
        response.should redirect_to(Universidad.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved universidad as @universidad" do
        # Trigger the behavior that occurs when invalid params are submitted
        Universidad.any_instance.stub(:save).and_return(false)
        post :create, {:universidad => { "nombre" => "invalid value" }}, valid_session
        assigns(:universidad).should be_a_new(Universidad)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Universidad.any_instance.stub(:save).and_return(false)
        post :create, {:universidad => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested universidad" do
        universidad = Universidad.create! valid_attributes
        # Assuming there are no other universidads in the database, this
        # specifies that the Universidad created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Universidad.any_instance.should_receive(:update_attributes).with({ "nombre" => "MyString" })
        put :update, {:id => universidad.to_param, :universidad => { "nombre" => "MyString" }}, valid_session
      end

      it "assigns the requested universidad as @universidad" do
        universidad = Universidad.create! valid_attributes
        put :update, {:id => universidad.to_param, :universidad => valid_attributes}, valid_session
        assigns(:universidad).should eq(universidad)
      end

      it "redirects to the universidad" do
        universidad = Universidad.create! valid_attributes
        put :update, {:id => universidad.to_param, :universidad => valid_attributes}, valid_session
        response.should redirect_to(universidad)
      end
    end

    describe "with invalid params" do
      it "assigns the universidad as @universidad" do
        universidad = Universidad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Universidad.any_instance.stub(:save).and_return(false)
        put :update, {:id => universidad.to_param, :universidad => { "nombre" => "invalid value" }}, valid_session
        assigns(:universidad).should eq(universidad)
      end

      it "re-renders the 'edit' template" do
        universidad = Universidad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Universidad.any_instance.stub(:save).and_return(false)
        put :update, {:id => universidad.to_param, :universidad => { "nombre" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested universidad" do
      universidad = Universidad.create! valid_attributes
      expect {
        delete :destroy, {:id => universidad.to_param}, valid_session
      }.to change(Universidad, :count).by(-1)
    end

    it "redirects to the universidads list" do
      universidad = Universidad.create! valid_attributes
      delete :destroy, {:id => universidad.to_param}, valid_session
      response.should redirect_to(universidads_url)
    end
  end

end
